name: lint

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main, development]

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - run: pnpm install
            - run: pnpm -r check
            - run: pnpm -r lint
